declare a, char
declare b, char
declare c, char
store 'a', c
declare x, real
declare &tempr1, real
itor 0, &tempr1
store &tempr1, x
declare y, real
declare &tempr2, real
itor 1, &tempr2
store &tempr2, y
declare k, integer
declare j, integer
declare &tempi3, integer
rtoi 2.5, &tempi3
store &tempi3, j
declare m, integer
declare n, boolean
store 1, n
